# Generated by Django 3.2 on 2021-12-29 09:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('starting_date', models.DateField()),
                ('total_members', models.IntegerField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.UUID('73d5a383-ee34-4be7-bdc6-e03c3c6f8d76'), max_length=255)),
                ('expiry_date', models.DateField(default=datetime.date(2022, 1, 13))),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='group.group')),
            ],
        ),
    ]
