# Generated by Django 3.2 on 2022-01-01 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_invitationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=uuid.UUID('fb543c5c-b064-495e-9d33-cac89f5da56d'), max_length=255),
        ),
    ]
