# Generated by Django 3.2 on 2022-01-01 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_invitationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=uuid.UUID('25140382-2c3a-4c97-bbdd-1a33a27de858'), max_length=255),
        ),
    ]
