# Generated by Django 3.2 on 2022-01-01 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0006_alter_invitationcode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationcode',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='usergrouppermission',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='usergrouppermission',
            old_name='permission_id',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='usergrouppermission',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=uuid.UUID('b1f98d8f-272e-4dde-9321-b867a4f5c034'), max_length=255),
        ),
        migrations.CreateModel(
            name='GeneratedNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_numbers', to='group.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
