# Generated by Django 3.2 on 2022-01-01 12:37

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0007_auto_20220101_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatednumber',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatednumber',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=uuid.UUID('a678ea6d-5887-4688-98d4-262cd50cbcfa'), max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='generatednumber',
            unique_together={('number', 'group', 'owner')},
        ),
    ]
