# Generated by Django 3.2 on 2022-01-03 17:26

import datetime
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0010_auto_20220101_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=uuid.UUID('8f7ed6ec-9e77-4a5b-a442-582e002fb5e7'), max_length=255),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2022, 1, 18)),
        ),
        migrations.AlterUniqueTogether(
            name='generatednumber',
            unique_together={('number', 'group'), ('owner', 'group')},
        ),
    ]
