# Generated by Django 3.2 on 2022-01-03 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20220103_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=uuid.UUID('a37d5990-91c9-4bc7-b8c3-2258b8eed696'), max_length=255),
        ),
    ]
