# Generated by Django 3.2 on 2022-01-09 07:33

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_alter_invitationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=uuid.UUID('c8b8fee5-d7d0-4568-b9fa-b44b559e5d82'), max_length=255),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2022, 1, 24)),
        ),
    ]
