# Generated by Django 3.2 on 2022-01-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupmembers', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
