# Generated by Django 3.2 on 2022-01-01 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20220101_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=uuid.UUID('4a913c98-2f97-4a8d-accd-3913ba59d970'), max_length=255),
        ),
    ]
