# Generated by Django 3.2 on 2022-01-01 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_invitationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=uuid.UUID('684ab886-5b27-4850-a5de-3d14503d9749'), max_length=255),
        ),
    ]
