# Generated by Django 3.2 on 2022-01-01 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20220101_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=uuid.UUID('0f2d6968-2bf9-479a-9537-f447ecc61673'), max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='generatednumber',
            unique_together={('number', 'group')},
        ),
    ]
