# Generated by Django 3.2 on 2022-01-01 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20220101_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatednumber',
            options={'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=uuid.UUID('d8cbaa3f-8a69-4950-868d-35e71cf8e430'), max_length=255),
        ),
    ]
