# Generated by Django 3.2 on 2022-01-10 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0015_rename_groupmembers_groupmember'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('member', 'group')},
        ),
    ]
